config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'errors/not_found'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get '/about', to: "home#about"
  get '/leaderboard', to: "home#leaderboard"
  get '/levels', to: "home#levels"

  match "/404", :to => "errors#not_found", :via => :all

  ## EASY LEVELS ##
  get "/easy/step_one" => "easy#step_one"
  get "/easy/step_two" => "easy#step_two"
  get "/easy/atlanta" => "easy#atlanta"
  get "/easy/step_three" => "easy#step_three"
  get "/easy/step_four" => "easy#step_four"
    ### THE RIDDLE ###
    get "/easy/riddle/voiceless" => "easy#riddle_voiceless"
    get "/easy/riddle/it_cries" => "easy#riddle_it_cries"
    get "/easy/riddle/wingless" => "easy#riddle_wingless"
    get "/easy/riddle/flutters" => "easy#riddle_flutters"
    get "/easy/riddle/touchless" => "easy#riddle_touchless"
    get "/easy/riddle/bites" => "easy#riddle_bites"
    get "/easy/riddle/mouthless" => "easy#riddle_mouthless"
    get "/easy/riddle/mutters" => "easy#riddle_mutters"
    get "/easy/riddle/key" => "easy#riddle_key"
    ###
  get "/easy/step_five" => "easy#step_five"
  get "/easy/step_six" => "easy#step_six"
  get "/easy/step_seven" => "easy#step_seven"
  get "/easy/step_eight" => "easy#step_eight"
  get "/easy/step_nine" => "easy#step_nine"
  get "/easy/step_ten" => "easy#step_ten"
  get "/easy/step_eleven" => "easy#step_eleven"
  get "/easy/step_twelve" => "easy#step_twelve"
  get "/easy/congrats" => "easy#congrats"


  ## MEDIUM LEVELS ##
  get "/medium/1" => "medium#level_1"


  ## HARD LEVELS ##
  get "/hard/level_1" => "hard#level_1"


  ## INSANE LEVELS ##



end

app/controllers/easy_controller.rb
class EasyController < ApplicationController
  before_action :authenticate_user!
  def step_one
    if !LevelUser.find_by(user_id: current_user.id, level_id: 1).present?
      redirect_to "/404"
    end
    @TITLE = ENV["STEP_ONE_TITLE"]
    if params[:shape].to_s == ENV["STEP_ONE_KEY"]
      @TITLE = "Enigma"
      if current_user.level_value < 2
        LevelUser.create!(user_id: current_user.id, level_id: 2)
        current_user.update!(current_level: "/easy/step_two", level_value: 2)
      end
      redirect_to easy_step_two_path
    end
  end

  def step_two
    if !LevelUser.find_by(user_id: current_user.id, level_id: 2).present?
      redirect_to "/404"
    end
  end

  def step_three
    if !LevelUser.find_by(user_id: current_user.id, level_id: 3).present?
      redirect_to "/404"
    end

    @please = false
    if params[:input].present?
      if params[:input].downcase == ENV["STEP_THREE_KEY"]
        if current_user.level_value < 4
          LevelUser.create!(user_id: current_user.id, level_id: 4)
          current_user.update!(current_level: "/easy/step_four", level_value: 4)
        end
        redirect_to easy_step_four_path
      elsif params[:input].downcase == ENV["STEP_THREE_TRAP"]
        @please = true
      else
        params[:input] = ""
      end
    end
  end

  def step_four
    if !LevelUser.find_by(user_id: current_user.id, level_id: 4).present?
      redirect_to "/404"
    end
  end

  def step_five
    if !LevelUser.find_by(user_id: current_user.id, level_id: 5).present?
      redirect_to "/404"
    end

    if params[:key].present? && params[:key] == ENV["STEP_FIVE_KEY"]
      if current_user.level_value < 6
        LevelUser.create!(user_id: current_user.id, level_id: 6)
        current_user.update!(current_level: "/easy/step_six", level_value: 6)
      end
      redirect_to easy_step_six_path
    end
    params[:key] = ""
  end

  def step_six
    if !LevelUser.find_by(user_id: current_user.id, level_id: 6).present?
      redirect_to "/404"
    end

    # if WIN
    #   if current_user.level_value < 7
    #     LevelUser.create!(user_id: current_user.id, level_id: 7)
    #     current_user.update!(current_level: "/easy/step_seven", level_value: 7)
    #   end
    #   redirect_to easy_step_seven_path
    # end
  end

  def step_seven
    if !LevelUser.find_by(user_id: current_user.id, level_id: 7).present?
      redirect_to "/404"
    end

#    if WIN
#      current_user.update!(current_level: "/easy/step_eight", level_value: 8)
#      redirect_to easy_step_eight_path
#    end
  end

  def step_eight
    if !LevelUser.find_by(user_id: current_user.id, level_id: 8).present?
      redirect_to "/404"
    end

#    if WIN
#      current_user.update!(current_level: "/easy/step_nine", level_value: 9)
#      redirect_to easy_step_nine_path
#    end
  end

  def step_nine
    if !LevelUser.find_by(user_id: current_user.id, level_id: 9).present?
      redirect_to "/404"
    end

#    if WIN
#      current_user.update!(current_level: "/easy/step_ten", level_value: 10)
#      redirect_to easy_step_ten_path
#    end
  end

  def step_ten
    if !LevelUser.find_by(user_id: current_user.id, level_id: 10).present?
      redirect_to "/404"
    end

#    if WIN
#      current_user.update!(current_level: "/easy/step_eleven", level_value: 11)
#      redirect_to easy_step_eleven_path
#    end
  end

  def step_eleven
    if !LevelUser.find_by(user_id: current_user.id, level_id: 11).present?
      redirect_to "/404"
    end

#    if WIN
#      current_user.update!(current_level: "/easy/step_twelve", level_value: 12)
#      redirect_to easy_step_twelve_path
#    end
  end

  def step_twelve
    if !LevelUser.find_by(user_id: current_user.id, level_id: 12).present?
      redirect_to "/404"
    end

#    if WIN
#      LevelUser.create!(user_id: current_user.id, level_id: 13)
#      current_user.update!(current_level: "/medium/1", level_value: 13)
#      redirect_to easy_congrats_path
#    end
  end

  def congrats

  end

###
### ETC, ETC...
###

### LEVEL UP HELPERS

  def atlanta
    if !LevelUser.find_by(user_id: current_user.id, level_id: 2).present?
      redirect_to "/404"
    end
    if current_user.level_value < 3
      LevelUser.create!(user_id: current_user.id, level_id: 3)
      current_user.update!(current_level: "/easy/step_three", level_value: 3)
    end
    redirect_to easy_step_three_path
  end

  def riddle_key
    if !LevelUser.find_by(user_id: current_user.id, level_id: 4).present?
      redirect_to "/404"
    end
    if params[:input].present?
      if params[:input].downcase == ENV["STEP_FOUR_KEY"] || params[:input].downcase == ENV["STEP_FOUR_KEY_ALT"]
        if current_user.level_value < 5
          LevelUser.create!(user_id: current_user.id, level_id: 5)
          current_user.update!(current_level: "/easy/step_five?key=", level_value: 5)
        end
        redirect_to easy_step_five_path(key: "")
      else
        params[:input] = ""
      end
    end
  end

end

app/helpers/easy_helper.rb
module EasyHelper
end

app/views/easy/congrats.html.slim
.container
  .is-size-1.has-text-centered
    | Congrats!
  br
  .is-size-4.has-text-centered
    | You made it through the easy levels. Let's spice things up a lil bit.
  br
  br
  .has-text-centered
    = active_link_to medium_1_path, class: "is-size-3 is-link", class_active: "is-active", active: :exact do
      | Take me to the Medium levels!

app/views/easy/riddle_bites.html.slim
.container
  .is-size-1.has-text-centered
    | STEP FOUR
  br
  .is-size-4.has-text-centered
    | Precious riddle
  br
  br
  .columns
    .column.is-4
      .has-text-centered
        = active_link_to easy_riddle_voiceless_path, class: "is-link is-size-4" do
          | 1
    .column.is-4
      .has-text-centered
        = active_link_to easy_riddle_mutters_path, class: "is-link is-size-4" do
          | 2
    .column.is-4
      .has-text-centered
        = active_link_to easy_riddle_wingless_path, class: "is-link is-size-4" do
          | 3
    br
    br
    br
    .has-text-centered
      = active_link_to easy_step_four_path, class: "is-link is-size-4" do
        | Go Back

app/views/easy/riddle_key.html.slim
.container
  br
  br
  br
  .is-size-2.has-text-centered
    | Key
  br
  .columns
    .column.is-5
    .column.is-2
      .field
        .control
          form
            div style="display:flex;align-items:center;"
              = text_field_tag :input, params[:input], method: :post, class: "input"
      br
      br
      br
      .has-text-centered
        = active_link_to easy_step_four_path, class: "is-link is-size-4" do
          | Go Back
    .column.is-5

app/views/easy/riddle_mouthless.html.slim
.container
  .is-size-1.has-text-centered
    | STEP FOUR
  br
  .is-size-4.has-text-centered
    | Precious riddle
  br
  br
  br
  .has-text-centered
    .is-size-3
      | Dead End
    br
    = active_link_to easy_riddle_it_cries_path, class: "is-link is-size-4" do
      | Go Back

app/views/easy/riddle_mutters.html.slim
.container
  .is-size-1.has-text-centered
    | STEP FOUR
  br
  .is-size-4.has-text-centered
    | Precious riddle
  br
  br
  br
  .has-text-centered
    .is-size-3
      | Dead End
    br
    = active_link_to easy_riddle_bites_path, class: "is-link is-size-4" do
      | Go Back

app/views/easy/riddle_touchless.html.slim
.container
  .is-size-1.has-text-centered
    | STEP FOUR
  br
  .is-size-4.has-text-centered
    | Precious riddle
  br
  br
  br
  .has-text-centered
    .is-size-3
      | Dead End
    br
    = active_link_to easy_riddle_it_cries_path, class: "is-link is-size-4" do
      | Go Back

app/views/easy/riddle_voiceless.html.slim
.container
  .is-size-1.has-text-centered
    | STEP FOUR
  br
  .is-size-4.has-text-centered
    | Precious riddle
  br
  br
  br
  .has-text-centered
    .is-size-3
      | Dead End
    br
    = active_link_to easy_riddle_bites_path, class: "is-link is-size-4" do
      | Go Back

app/views/easy/riddle_wingless.html.slim
.container
  .is-size-1.has-text-centered
    | STEP FOUR
  br
  .is-size-4.has-text-centered
    | Precious riddle
  br
  br
  br
  .has-text-centered
    .is-size-3
      | Dead End
    br
    = active_link_to easy_riddle_bites_path, class: "is-link is-size-4" do
      | Go Back

app/views/easy/step_four.html.slim
.container
  .is-size-1.has-text-centered
    | STEP FOUR
  br
  .is-size-4.has-text-centered
    | Precious riddle
  br
  br
  .columns
    .column.is-4
      .has-text-centered
        = active_link_to easy_riddle_it_cries_path, class: "is-link is-size-4" do
          | 1
    .column.is-4
      .has-text-centered
        = active_link_to easy_riddle_key_path, class: "is-link is-size-4" do
          | 2
    .column.is-4
      .has-text-centered
        = active_link_to easy_riddle_bites_path, class: "is-link is-size-4" do
          | 3

app/views/easy/step_nine.html.slim
.container
  .is-size-1.has-text-centered
    | STEP NINE

app/views/easy/step_one.html.slim
.container
  .is-size-1.has-text-centered
    | STEP ONE
  br
  .is-size-4.has-text-centered
    | The voices in my Head..
  br
  br
  = form_tag '/easy/step_one', method: :get do
    - for i in 0..5
      .columns
        .column.is-3
        .column.is-6.header-row
          - for j in 0..5
              = check_box_tag "shape[]", false, false, value: "#{i}-#{j}", class: "is-large"
        .column.is-3
      br
    .has-text-centered
      = submit_tag 'Submit', class: "button"

app/views/easy/step_six.html.slim
.container
  .is-size-1.has-text-centered
    | STEP SIX
  br
  .is-size-4.has-text-centered
    | description
  br
  br
  .columns

app/views/easy/step_ten.html.slim
.container
  .is-size-1.has-text-centered
    | STEP TEN

app/views/easy/step_twelve.html.slim
.container
  .is-size-1.has-text-centered
    | STEP TWELVE