config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'errors/not_found'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get '/about', to: "home#about"
  get '/leaderboard', to: "home#leaderboard"
  get '/levels', to: "home#levels"

  match "/404", :to => "errors#not_found", :via => :all

  ## EASY LEVELS ##
  get "/easy/step_one" => "easy#step_one"
  get "/easy/step_two" => "easy#step_two"
  get "/easy/atlanta" => "easy#atlanta"
  get "/easy/step_three" => "easy#step_three"
  get "/easy/step_four" => "easy#step_four"
    ### THE RIDDLE ###
    get "/easy/riddle/voiceless" => "easy#riddle_voiceless"
    get "/easy/riddle/it_cries" => "easy#riddle_it_cries"
    get "/easy/riddle/wingless" => "easy#riddle_wingless"
    get "/easy/riddle/flutters" => "easy#riddle_flutters"
    get "/easy/riddle/touchless" => "easy#riddle_touchless"
    get "/easy/riddle/bites" => "easy#riddle_bites"
    get "/easy/riddle/mouthless" => "easy#riddle_mouthless"
    get "/easy/riddle/mutters" => "easy#riddle_mutters"
    get "/easy/riddle/key" => "easy#riddle_key"
    ###
  get "/easy/step_five" => "easy#step_five"
  get "/easy/step_six" => "easy#step_six"
  get "/easy/step_seven" => "easy#step_seven"
  get "/easy/step_eight" => "easy#step_eight"
  get "/easy/step_nine" => "easy#step_nine"
  get "/easy/step_ten" => "easy#step_ten"
  get "/easy/step_eleven" => "easy#step_eleven"
  get "/easy/step_twelve" => "easy#step_twelve"
  get "/easy/congrats" => "easy#congrats"


  ## MEDIUM LEVELS ##
  get "/medium/1" => "medium#level_1"


  ## HARD LEVELS ##
  get "/hard/level_1" => "hard#level_1"


  ## INSANE LEVELS ##



end

app/views/layouts/_nav.html.slim
.nav.navbar.is-fixed-top.is-dark role="navigation" aria-label="dropdown navigation"
  .container
    .navbar-brand
      a.navbar-item href="/"
        | Enigma
      span.navbar-burger id="nav-toggle" class="nav-toggle" onclick="document.getElementById('nav-menu').classList.toggle('is-active');"
        span
        span
        span
    .navbar-menu id='nav-menu'
      .navbar-start
        = active_link_to leaderboard_path, class: "navbar-item" do
          | Leaderboard
        = active_link_to about_path, class: "navbar-item" do
          | About
      .navbar-end
        - if current_user.present?
          = active_link_to levels_path, class: "navbar-item is-info" do
            | Levels List
          = active_link_to current_user.current_level, class: "navbar-item is-info" do
            | Resume
          = active_link_to destroy_user_session_path, method: :delete, class: "navbar-item" do
            | #{current_user.username} - Log out
        - else
          = active_link_to new_user_session_path, class: "navbar-item" do
            | Log In

#navbar-padder

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    title
      = @TITLE
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render "layouts/nav"
    = yield